Resources:
  ChatTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: sortKey
        AttributeType: S
      - AttributeName: data
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: sortKey
        KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
      - IndexName: sortKey-data-index
        KeySchema:
        - AttributeName: sortKey
          KeyType: HASH
        - AttributeName: data
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}